version: "3.8"
services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/api
    environment:
      JSON_SECRET: ac41134609becfe9a354e96b4a3127d6da5591bfd6267cd054964c0919c0fc18
    ports:
      - 8888:8000
  worker:
    build: .
    command: rq worker -u redis://redis:6379/0 --name worker_name_2 default_queue_name
    volumes:
      - ./src:/api
    depends_on:
      - redis
  dashboard:
    build: .
    command: rq-dashboard -b 0.0.0.0 -p 9181 --redis-url redis://redis:6379/0
    ports:
      - 9181:9181
    volumes:
      - ./src:/api
    environment:
      - RQ_DASHBOARD_USERNAME=rq
      - RQ_DASHBOARD_PASSWORD=password
    depends_on:
      - redis
  redis:
    image: redis

